project:
  type: website

website:
  title: "Riley Finn"
  navbar:
    logo: images/salmon.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: tools.qmd
        text: Interactive
    right: 
      - href: contact.qmd
        text: Contact
      - href: updates.qmd
        text: Updates
    tools:
      - icon: github
        href: https://github.com/rileyfinn
      - icon: substack
        href: https://substack.com/@rileyfinn?
  page-footer: 
    left: "Copyright 2025, Riley Finn"
    center: |
      ![](images/salmon.png){width=150px}
    right: "Nanaimo, BC"
    


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    backgroundcolor: "#dbd3b8"

editor: visual

